# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a91315140b7266fd4163c65d60e66014dd689c29666c2619e6011cf57648df7f7d08fa25c8c6f40cb9bae77d5a87dca4651cf99117e32de7be8342cc97cbbcbb

test:
  secret_key_base: 37408ed4aaf4f9bc2fd909a6c0671819376e6202901ce693480f2c931215293235759b1f068c1fbfe466458725b8a5e48893a109806601256d262719fb25bfd2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
